[theme]
base = "light"
primaryColor = "#f63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# [theme.dark]
# base="dark"
# primaryColor="#c98bdb"
# backgroundColor="#0e1117"
# secondaryBackgroundColor="#262730"
# textColor="#fafafa"
